### ISSUE TITLE
Graph algorithms for HetNets

### ISSUE THREAD

**Issue by mutandon** [greenelab/connectivity-search-analyses#56]
Hi all, 

since you are working with heterogeneous information networks, I think it is interesting to point out a couple of works that might help you in this regard. 

* Some work on **metapaths** that are abstract description of paths surrounding a specific node.
They are useful in order to compare nodes in the graph.

Meng, C., Cheng, R., Maniu, S., Senellart, P., & Zhang, W. (2015). Discovering Meta-Paths in Large Heterogeneous Information Networks (pp. 754–764). Presented at the the 24th International Conference, New York, New York, USA: ACM Press. http://doi.org/10.1145/2736277.2741123

Sun, Y., 0001, J. H., Yan, X., Yu, P. S., & Wu, T. (2011). PathSim - Meta Path-Based Top-K Similarity Search in Heterogeneous Information Networks. Pvldb. 

* **Graph embeddings**: project the graph into a multi-dimensional space and perform similarity operations in that space (e.g., k-means): 

Chen, Y., & Wang, C. (2017). HINE: Heterogeneous Information Network Embedding. In Database Systems for Advanced Applications (Vol. 10177, pp. 180–195). Cham: Springer International Publishing. http://doi.org/10.1007/978-3-319-55753-3_12

metapath2vec: https://www.youtube.com/watch?v=t9yujaCpX_E

* Some work on node classification: 

 http://www.cs.cmu.edu/~deswaran/papers/vldb17-zoobp.pdf

These are just a few, but if you tell me what you need there might be more customized ideas out there! 

Regards, 
Davide

**Comment by dhimmel** [comment]
Adding another reference to a related work named [MetaExp](https://meta-exp.github.io/) mentioned to me by @jexp. From their manuscript titled [MetaExp: Interactive Explanation and Exploration of Large Knowledge Graphs](https://meta-exp.github.io/resources/paper.pdf):

> We present MetaExp, a system that assists the user during the exploration of large knowledge graphs, given two sets of initial nodes. At its core, MetaExp presents a small set of meta-paths to the user, which are sequences of relationships among node types. Such meta-paths do not overwhelm the user with complex structures, yet they preserve semantically-rich relationships in a graph. MetaExp engages the user in an interactive procedure, which involves simple meta-paths evaluations to infer a user-specific similarity measure. This similarity measure incorporates the domain knowledge and the preferences of the user, overcoming the fundamental limitations of previous methods based on local node neighborhoods or statically determined similarity scores. Our system provides a userfriendly interface for searching initial nodes and guides the user towards progressive refinements of the meta-paths. The system is demonstrated on three datasets, Freebase, a movie database, and a biological network.
